### PR TITLE
feat(ruler-game):rework the ruler game

### LINKED ISSUE #79: Rework the Ruler catching game
**Is your feature request related to a problem? Please describe.**
The ruler game is hard to tap on

**Describe the solution you'd like**
To have the ruler game be reworked into a kill the roaches game where you tap on the screen.
Also have a quick splash screen telling the player what to do

### PR DESCRIPTION
**Pull request by Lap343**
## Changes
1. Change the catch the ruler game to squish the roach

## Purpose
Squishing a roach is a better game

Closes #79

### CODE REVIEW

**Review by BlackCubes — APPROVED** [review]
SQUISH IT!!!!!!!!!!!!!!!!!!!!

**Review by JorgeLVilla — APPROVED** [review]
Beast modeeee!

**Comment by dannysanchez559** [comment]
cool

**Review by dannysanchez559 — COMMENTED** [review]
:cockroach:

**Pull request merged**
